MAINT: Refactoring filtering functions
bokulich-lab/q2-minimap2 pull request #16
Opened 2024-04-29 14:21 UTC by ChristosMatzoros

2024-05-01 15:35 UTC, ChristosMatzoros commented
This PR aims to explore any additional enhancements for the two filtering actions, `filter_paired_end_reads` and `filter_single_end_reads`, and to review the existing codebase for both.

2024-05-14 13:17 UTC, VinzentRisch commented
add_mapped_paired_read_flags
- add test 
- maybe add a docstring

2024-05-17 10:05 UTC, ChristosMatzoros commented
Hey @VinzentRisch,

I made the changes you suggested and added the tests. I also merged `add_mapped_paired_read_flags()` and `process_paired_unmapped_flags()` functions into one simpler function (`process_paired_sam_flags()`). Please have a look and let me know. Thank you

2024-05-28 08:59 UTC, ChristosMatzoros commented
Dear @VinzentRisch,

I added a necessary test for paired-end reads, and now I think its ready. Please have a look and let me know if something else is needed.  

Thanks

2024-05-29 09:07 UTC, VinzentRisch requested changes
Hey :) see some changes below.

2024-05-29 12:25 UTC, VinzentRisch commented on q2_minimap2/_filtering_utils.py
>                      ):
```suggestion
                       if not min_per_identity or identity_percentage >= min_per_identity:
```
This fits on one line. I think it is easier to read

2024-05-30 09:23 UTC, VinzentRisch approved these changes
Hey looks good :)

2024-05-30 09:24 UTC, merged